name: 🗪 Chat - Change Request
description: "Change anything about the SCRF Community Discord Chat server"
title: "🗪 [🚧] Change Request"
labels: [chat]
assignees:
  - SirAh0
body:
  - type: markdown
    attributes:
      value: |
        ### Ownership of Change
        As the submitter of this change request you are in charge of its success.

        ### On Brand Review
        Any reqeusts to change or add images or words needs to pass through the [Document Pipeline](http://urltodocumentpipeline) (need url) @marvino3

        ### Make Change Requests Unique
        Each Change Request submitted should represent a single change or a change in singular scope. Each change should be tracked as it's own issue.

        ### How to 🚀 Launch
        Changes to Discord are made on a set schedule of `🚀 Launch Windows`. 
        
        In order for this change to go live, the below `Launch Ready Task List` must be completed before the opening of the next `🚀 Launch Window`.

        Once this task list is complete the change request is ⛽Fueled and scheduled to launch.
        
        For a list of launch windows please see the [Launch Window View](https://github.com/orgs/smartcontractresearchforum/projects/31/views/2) 

  
  - type: textarea
    id: tasks
    attributes:
      label: Launch Ready Task List
      description: The following set of tasks must be accomplished for the change to go live.
      value: |        
        ### Launch Ready Task List
        - [ ] Schedule a meet with @SirAh0 to implement the change on test server
        - [ ] Pick a launch window for this change to go live 
        - [ ] Ensure your change is launch ready before the launch window
        - [ ] After a month, schedule a follow up meeting with @SirAh0 to explain why this change was a success
        - [ ] Document pipeline approval, if applicable @marvino3

  - type: textarea
    id: benefit
    attributes:
      label: Benefits
      description: How will this change benefit the SCRF Community?

  - type: textarea
    id: request
    attributes:
      label: Change Request
      description: Describe what the change is, what it's going to do, and how to measure success of the change.

  - type: textarea
    id: people
    attributes:
      label: People
      description: Who is a part of this change?
      placeholder: |
        - @GitHub-Username
        - @GitHub-Username
