name: 🗪 Chat Change Request
description: "Change anything about the SCRF Community Discord Chat server"
title: "🗪 - Change Request"
labels: [chat]
assignees:
  - SirAh0
body:
  - type: markdown
    attributes:
      value: |
        ### Discord Change Lifecyle
        In order to get your change live on discord the following must occur.
        - a thing.
        - another thing.        
  - type: textarea
    id: text
    attributes:
      label: Issue Text
      description: "Describe your request."
      value: |
        - [ ] a thing
        - [ ] another thing
      