name: Announcement Request
description: If you have something to share with the SCRF community let us know!
title: "Announcement Request - "
labels: [chat]
assignees:
  - SirAh0
body:
  - type: markdown
    attributes:
      value: |
        TBD - Coming soon! see issue [#132](https://github.com/smartcontractresearchforum/IT/issues/132)

  - type: textarea
    id: text
    attributes:
      label: Describe the request
      description: Please be as complete as possible with information such as the when, where, cadence, URLs, post content etc. 