name: 🗪 Chat - Bad Bot
description: A bot is doing something wrong or isnt working at all. 
title: "🗪 [🤖] Bad Bot"
labels: [bug, chat]
assignees:
  - SirAh0
body:
  - type: markdown
    attributes:
      value: |
        ...the telemetrists began to use a computer to program the computer that designed the program for the computer that programmed the robot-controlling computer. 
        There was nothing but `confusion`. 
        *— Isaac Asimov*
  
  - type: input
    id: bot-name
    attributes:
      label: Bot Name
      description: Identify the misguided bot.

  - type: textarea
    id: text
    attributes:
      label: Describe Problem