name: 🗪 Chat - 🔓 User Role
description: SCRF Member needs a role change
title: "🗪 [🔓] UAR"
labels: [bug, chat]
assignees:
  - SirAh0
body:
  - type: markdown
    attributes:
      value: |
        Request a change of User Role

  - type: textarea
    id: text
    attributes:
      label: Request
      description: List the discord user name and the role they need or channel they need access to.
      placeholder: |
        - DiscordUser#123