name: 🗪 Chat - Calendar 
description: Something is wrong with a calendar listing
title: "🗪 [📅] Calendar"
labels: [bug, chat]
assignees:
  - SirAh0
body:
  - type: markdown
    attributes:
      value: |
        ### Requesting New Events
        If you would like to add a new event to the SCRF calendar, please open [📅 Add New Calendar Event](https://github.com/smartcontractresearchforum/discovery/issues/new?assignees=&labels=&template=calendar.yml&title=%F0%9F%93%85+-+New+Event) issue

  - type: textarea
    id: text
    attributes:
      label: Describe Problem