

name: 🗃️ - New Job Listing
description: Add a new job listing for SCRF 
title: "🗃️ - New Job Listing"
labels: ["🗃️ New Job"]
assignees:
  - ttaloute
body:
  - type: markdown
    attributes:
      value: |
        ### How to List a New Job
        1. New Role Proposal (copy doc and fill out areas)
        >[JD Template](https://docs.google.com/document/d/1whK2If1FmwCbjw3rdpVLPhMRiQutwtOug6kDK5so2BY/edit)

        2. Fill out the fields below in this issue.

        3. Complete the below task list.
        

        ### Complection Check List
        - [ ] New Role Proposal Complete (team head/lead)
        - [ ] Approved by Operations (to be checked by operations)
        - [ ] JD Complete
        - [ ] Reviewed on Docs Board
        - [ ] Posted on Github Docs
        - [ ] Posted on Job boards
        - [ ] Role filled

  - type: input
    id: team
    attributes:
      label: Team
    validations:
      required: true             

  - type: input
    id: rolename
    attributes:
      label: New Role Name
    validations:
      required: true       

  - type: input
    id: role-proposal-url
    attributes:
      label: Role Proposal URL
      description: Please enter the URL of the completed New Role Proposal JD Template.
    validations:
      required: true 